
const app = document.getElementById('app');
const scenes = {
runner:{kicker:'MOMENT 01 / EAST QUAY / 22:42',title:'The Runner',body:'A young runner cuts across the quay with a sealed manifest under his coat. Nobody else seems to notice.',choices:[['FOLLOW HIM','follow','Keep your distance. Learn first.'],['CALL JAX','jax','Jax can close the distance without making the scene loud.'],['INTERCEPT','intercept','Step into his path and make the first move.'],['LET HIM GO','letgo','Memorize the route.']]},
follow:{kicker:'MOMENT 02 / THE TRAIL / 22:58',title:'You Follow',body:'The runner checks Gate 3 and heads toward the warehouse district.',choices:[['ASK MARA','mara','Turn observation into social intelligence.'],['KEEP WATCHING','watch','Learn the pattern yourself.']]},
jax:{kicker:'MOMENT 02 / EAST QUAY / 22:51',title:'Jax Gets There First',body:'Jax appears with a stolen scrap of manifest paper. “Same runner, three nights.”',choices:[['TAKE THE MANIFEST','manifest','Trade speed for evidence.'],['SEND JAX AHEAD','jaxahead','Let your network move.']]},
intercept:{kicker:'MOMENT 02 / EAST QUAY / 22:50',title:'The First Gamble',body:'You stop the runner. He bolts. You catch the manifest, but the quay hears the shout.',choices:[['READ THE MANIFEST','manifest','Use the evidence.'],['ASK MARA TO CLEAN IT UP','mara','Let the social layer absorb your mistake.']]},
letgo:{kicker:'MOMENT 02 / GATE 3 / 23:05',title:'You Let Him Run',body:'You did not catch the courier. You caught the system: the guard changes shifts early.',choices:[['WATCH THE SHIFT','watch','Turn patience into an advantage.'],['ASK JAX TO TRACE HIM','jaxahead','Follow the network.']]},
mara:{kicker:'MOMENT 03 / MARA’S TABLE / 23:18',title:'Read the Room',body:'Mara says Corvin is pretending to help. “People perform innocence when they need you looking elsewhere.”',choices:[['PRESS CORVIN','pressure','Test the merchant.'],['FOLLOW THE MONEY','money','Find who is being paid.']]},
manifest:{kicker:'MOMENT 03 / THE MANIFEST / 23:12',title:'A Name on Paper',body:'The manifest lists Warehouse 9 and a payment to Venn, the Gate 3 guard.',choices:[['FIND THE SHIFT','watch','Confirm the route.'],['GO TO WAREHOUSE 9','warehouse','Move before the cargo leaves.']]},
watch:{kicker:'MOMENT 03 / GATE 3 / 23:20',title:'The Eight-Minute Window',body:'The guard rotation leaves Gate 3 exposed for roughly eight minutes.',choices:[['CHECK THE LEDGER','ledger','Find who paid for it.'],['MOVE ON WAREHOUSE 9','warehouse','Exploit the opening.']]},
jaxahead:{kicker:'MOMENT 03 / WAREHOUSE DISTRICT / 23:16',title:'Jax Finds the Thread',body:'Jax finds a route: sealed crates are staging at Warehouse 9.',choices:[['GET THE LEDGER','ledger','Turn a hunch into leverage.'],['GO TO WAREHOUSE 9','warehouse','You have enough to act.']]},
pressure:{kicker:'MOMENT 04 / CORVIN’S OFFICE / 23:31',title:'Pressure',body:'You mention Venn. Corvin offers money to make the questions stop.',choices:[['TAKE THE MONEY','take','Profit now.'],['REFUSE','ledger','Make the accusation matter.']]},
money:{kicker:'MOMENT 04 / THE LEDGER / 23:34',title:'Follow the Money',body:'The ledger confirms Corvin paid Venn to protect the shift window.',choices:[['FORM THE THEORY','theory','Commit to a plan.'],['KEEP DIGGING','dig','Spend more time.']]},
ledger:{kicker:'MOMENT 04 / THE LEDGER / 23:36',title:'The Missing Piece',body:'Corvin, Venn, and Warehouse 9 now connect.',choices:[['FORM THE THEORY','theory','Commit to a plan.'],['BRING IN SOL','sol','Invest in a deeper investigation.']]},
warehouse:{kicker:'MOMENT 04 / WAREHOUSE 9 / 23:40',title:'The Door',body:'Warehouse 9 is dark except for a line of light. Crates move inside. The next decision is how you want to be remembered.',choices:[['GHOST','ghost','Slip inside unseen.'],['FACE','face','Walk through with Mara.'],['STATEMENT','force','Enter openly.'],['LEVER','lever','Turn Venn before anyone draws a weapon.']]},
take:{kicker:'MOMENT 05 / THE PRICE / 23:36',title:'A Complication',body:'You take the money. Now you carry a secret of your own.',choices:[['GO TO WAREHOUSE 9','warehouse','Finish what you started.']]},
dig:{kicker:'MOMENT 05 / TOO LATE / 00:02',title:'The Window Closes',body:'You keep digging. The cargo leaves. Now you must track the shipment.',choices:[['FORM THE THEORY','theory','Build the next move.']]},
sol:{kicker:'MOMENT 05 / SOL’S ROOM / 23:45',title:'The Scholar',body:'Sol sees what you missed: Warehouse 9 is only the staging point.',choices:[['FORM THE THEORY','theory','Complete the picture.']]}
};
const cards=[['STRIKE',1,8,'Deal 8 damage.'],['FEINT',1,4,'Deal 4 damage. Gain Flow.'],['VAULT',1,5,'Deal 5 damage. Evade.'],['COUNTER',2,12,'Deal 12 if the enemy attacks.'],['DISARM',2,7,'Deal 7 damage. Weaken.'],['ESCAPE',2,0,'Leave safely.']];
function fresh(){return{version:4,day:7,time:1362,money:340,rep:17,intel:4,screen:'story',scene:'runner',missionComplete:false,theory:'',clues:[],recruited:['mara','jax'],combat:null,log:['The network is quiet. That usually means something is about to happen.']};}
let state;try{const s=JSON.parse(localStorage.getItem('youngLegendSave')||'null');state=s&&s.version===4?s:fresh();}catch(e){state=fresh();}
const appEl=document.getElementById('app');
function save(){localStorage.setItem('youngLegendSave',JSON.stringify(state));}
function timeText(){return String(Math.floor(state.time/60)%24).padStart(2,'0')+':'+String(state.time%60).padStart(2,'0');}
function advance(n){state.time+=n;if(state.time>=1440){state.day++;state.time-=1440;}}
function esc(s){return String(s).replace(/[&<>]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});}
function header(t,s){return '<div class="hero"><div><div class="eyebrow">YOUNG LEGEND / DAY '+String(state.day).padStart(2,'0')+' / '+timeText()+'</div><h1 class="title">'+t+'</h1><p class="subtitle">'+s+'</p></div></div>';}
function shell(content,locked){appEl.innerHTML='<div class="shell"><aside class="sidebar"><div class="mark">YL</div><nav class="nav"><button '+(locked?'disabled':'')+' onclick="go(\'network\')">◆ Network</button><button '+(locked?'disabled':'')+' onclick="go(\'investigate\')">⌕ Investigate</button><button '+(locked?'disabled':'')+' onclick="go(\'operation\')">◇ Operations</button><button onclick="go(\'progress\')">↗ Progress</button></nav><div class="sidebar-foot">BUILD THE NETWORK.<br>READ THE ROOM.<br>BE REMEMBERED.</div></aside><header class="top"><div class="brand"><small>SLU / CHARACTER RPG</small>YOUNG LEGEND</div><div class="top-meta"><div class="pill">◈ <b>'+state.money+'</b> crowns</div><div class="pill">◆ <b>'+state.rep+'</b> legend</div><div class="pill">⌁ <b>'+state.intel+'</b> intel</div><div class="pill">AP <b>6/6</b></div></div></header><main class="main">'+content+'</main></div>';}
function renderStory(){const s=scenes[state.scene]||scenes.runner;let choices='<div class="choice-list">';s.choices.forEach(function(c,i){choices+='<button class="choice" onclick="choose(\''+c[1]+'\')"><span class="choice-num">0'+(i+1)+'</span><div><b>'+c[0]+'</b><small>'+c[2]+'</small></div></button>';});choices+='</div>';shell('<div class="story-card screen"><div class="story-kicker">'+s.kicker+'</div><div class="story-layout"><div class="story-copy"><h1>'+s.title+'</h1><p>'+s.body+'</p>'+choices+'</div><aside class="story-side"><div class="scene-symbol">YL</div><div class="section-title">THE RULE</div><p class="muted">Every choice costs time, creates information, or changes how people see you.</p><div class="clock-card"><span>LOCAL TIME</span><b>'+timeText()+'</b><small>Deadline: midnight cargo movement</small></div></aside></div></div>',true);}
function choose(next){const cost={follow:16,jax:9,intercept:8,letgo:23,mara:18,watch:12,manifest:10,jaxahead:14,pressure:13,money:12,warehouse:4,take:5,theory:3,dig:26,ledger:8,sol:10};advance(cost[next]||10);if(next==='theory'){state.theory='Corvin is staging the missing shipments at Warehouse 9, using Venn and the shift gap to move them.';state.rep+=3;state.screen='operation';save();render();return;}if(['ghost','face','force','lever'].includes(next)){startCombat(next);return;}state.scene=next;save();render();}
function renderOperation(){shell(header('The Operation','Your investigation has produced a target. Choose how the story becomes legend.')+'<div class="op-grid"><section class="card section"><div class="section-title">WAREHOUSE 9 / '+timeText()+'</div><p class="subtitle">The crates are moving. Your theory points to Corvin, Venn, and the shift gap.</p><div class="approaches"><button class="approach" onclick="startCombat(\'ghost\')"><span class="risk">LOW RISK</span><b>THE GHOST</b><small>Slip through the service route.</small></button><button class="approach" onclick="startCombat(\'face\')"><span class="risk">SOCIAL</span><b>THE FACE</b><small>Let Mara open the room.</small></button><button class="approach" onclick="startCombat(\'force\')"><span class="risk">HIGH RISK</span><b>THE STATEMENT</b><small>Enter openly.</small></button><button class="approach" onclick="startCombat(\'lever\')"><span class="risk">NETWORK</span><b>THE LEVER</b><small>Turn Venn before anyone draws a weapon.</small></button></div></section><aside class="card section"><div class="section-title">YOUR THEORY</div><p class="muted">'+esc(state.theory)+'</p></aside></div>',false);}
function startCombat(method){state.combat={method:method,enemy:42,hp:40,energy:3,turn:0,evade:false,weakened:false,flow:method==='ghost'?1:0,msg:'The room reacts.'};render();}
function renderCombat(){const c=state.combat;if(c.method==='lever'){shell('<div class="story-card screen"><div class="story-kicker">WAREHOUSE 9 / '+timeText()+'</div><div class="story-copy"><h1>The Lever</h1><p>Venn knows what happens if the payment becomes public. You offer him one clean exit.</p><div class="choice-list"><button class="choice" onclick="completeMission(true)"><span class="choice-num">01</span><div><b>MAKE THE DEAL</b><small>Recover the shipment without a fight.</small></div></button><button class="choice" onclick="startCombat(\'force\')"><span class="choice-num">02</span><div><b>BREAK THE DEAL</b><small>Make the room answer to you.</small></div></button></div></div></div>',true);return;}let hand='';cards.forEach(function(card){hand+='<button class="card-btn" onclick="playCard(\''+card[0]+'\')" '+(c.energy<card[1]?'disabled':'')+'><span class="card-cost">'+card[1]+'</span><b>'+card[0]+'</b><small>'+card[3]+'</small></button>';});shell('<div class="combat-wrap screen">'+header('Make your move.','Combat is the resolution layer. Read intent, build Flow, and leave with a story.')+'<div class="combat-board"><div class="combat-top"><div class="fighter"><div class="name">YOUNG LEGEND</div><div class="hp"><i style="width:'+(c.hp/40*100)+'%"></i></div><div class="intent">HP '+c.hp+'/40 · FLOW '+c.flow+'</div></div><div class="fighter" style="text-align:right"><div class="name">WAREHOUSE GUARD</div><div class="hp"><i style="width:'+(c.enemy/42*100)+'%"></i></div><div class="intent">'+(c.turn%2===0?'ATTACK — 7 DAMAGE':'GUARD — RECOVER 2')+'</div></div></div><div class="arena"><div class="avatar">YL</div><div class="vs">VS</div><div class="avatar enemy">WG</div></div><div class="combat-footer"><div class="energy">ENERGY <b>'+c.energy+'/3</b> · '+esc(c.msg)+'</div><div class="hand">'+hand+'</div></div></div></div>',false);}
function playCard(name){const c=state.combat,card=cards.find(function(x){return x[0]===name;});if(!card||c.energy<card[1])return;c.energy-=card[1];if(name==='ESCAPE'){completeMission(false);return;}let dmg=card[2];if(name==='FEINT')c.flow++;if(name==='VAULT')c.evade=true;if(name==='DISARM')c.weakened=true;if(name==='COUNTER'&&c.turn%2!==0){dmg=0;c.hp-=3;c.msg='You countered too early.';}else{c.enemy-=dmg;c.msg=name+' lands for '+dmg+'.';}if(c.enemy<=0){completeMission(true);return;}if(c.turn%2===0){if(c.evade){c.evade=false;c.msg+=' You slipped the return strike.';}else c.hp-=c.weakened?3:7;}else c.enemy=Math.min(42,c.enemy+2);c.turn++;c.energy=3;if(c.hp<=0){completeMission(false);return;}render();}
function completeMission(win){state.missionComplete=true;state.rep=Math.max(0,state.rep+(win?12:-2));state.money+=win?180:0;state.log.unshift(win?'The Missing Shipment is resolved. Your first legend is earned.':'The operation ended without the result you wanted.');state.combat=null;state.screen='network';save();render();}
function statBox(a,b,c){return'<div class="card stat"><div class="label">'+a+'</div><div class="value">'+b+'</div><div class="delta">'+c+'</div></div>';}
function renderNetwork(){shell(header('The Network','The mission is complete. Now the city opens up.')+'<div class="grid stats">'+statBox('MONEY',state.money,'operational income')+statBox('LEGEND',state.rep,'reputation')+statBox('INTEL',state.intel,'knowledge')+statBox('TIME',timeText(),'the city keeps moving')+statBox('NETWORK',state.recruited.length,'connections')+'</div><div class="grid cols"><section class="card section"><div class="section-title">THE MISSING SHIPMENT</div><p class="muted">Resolved. Your first defining operation is complete.</p><button class="btn primary" onclick="continueDay()">CONTINUE TO DAY '+(state.day+1)+'</button></section><section class="card section"><div class="section-title">Recent word</div><div class="log">'+state.log.map(function(x){return'<div class="logline"><span>LOG</span>'+esc(x)+'</div>';}).join('')+'</div></section></div>',false);}
function renderProgress(){shell(header('Become Someone','Your build is the pattern of choices you keep making.')+'<div class="card section"><div class="section-title">Legend</div><p class="muted">Your reputation is shaped by the methods you choose, not a class screen.</p></div>',false);}
function continueDay(){state.day++;state.time=540;save();renderNetwork();}
function go(screen){if(!state.missionComplete&&screen!=='progress')return;state.screen=screen;render();}
function render(){if(state.combat)return renderCombat();if(!state.missionComplete)return renderStory();if(state.screen==='operation')return renderOperation();if(state.screen==='progress')return renderProgress();renderNetwork();}
window.choose=choose;window.startCombat=startCombat;window.playCard=playCard;window.completeMission=completeMission;window.go=go;window.continueDay=continueDay;render();
